# Generated by Django 2.0.13 on 2019-04-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_Date', models.DateTimeField()),
                ('log_Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Billing_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_Tax', models.IntegerField()),
                ('invoice_Prefix', models.CharField(max_length=20)),
                ('invoice_Deadline', models.DateField()),
                ('invoice_Header', models.TextField()),
                ('invoice_Footer', models.TextField()),
                ('card_Statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_Allows', models.BooleanField()),
                ('booking_Advance', models.TimeField()),
                ('booking_Limit', models.IntegerField()),
                ('booking_Overwrite', models.TimeField()),
                ('booking_Refund', models.BooleanField()),
                ('booking_Lock', models.IntegerField()),
                ('booking_Info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_Start', models.DateTimeField()),
                ('booking_End', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_Name', models.CharField(max_length=50)),
                ('pairing_Key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_Name', models.CharField(max_length=50)),
                ('equipment_Desc', models.TextField()),
                ('equipment_Fee', models.IntegerField()),
                ('power_Consumption', models.IntegerField()),
                ('busy_Time', models.TimeField()),
                ('idle_Time', models.TimeField()),
                ('require_Training', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('bookable', models.BooleanField()),
                ('booking_Fee', models.IntegerField()),
                ('booking_Granul', models.TimeField()),
                ('equipment_Bridge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Bridge')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_Name', models.CharField(max_length=50)),
                ('invite_New', models.BooleanField()),
                ('currency', models.CharField(max_length=50)),
                ('data_Retention', models.DateField()),
                ('contact_Email', models.EmailField(max_length=254)),
                ('contact_Website', models.CharField(max_length=50)),
                ('contact_Phone', models.IntegerField()),
                ('billing_Opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Billing_opt')),
                ('booking_Opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Booking_opt')),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_Name', models.CharField(max_length=20)),
                ('opt_Week', models.BooleanField()),
                ('opt_Evening', models.BooleanField()),
                ('opt_Time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_Name', models.CharField(max_length=30)),
                ('package_Describ', models.CharField(max_length=50)),
                ('package_Note', models.TextField()),
                ('package_Price_Reccuring', models.IntegerField()),
                ('package_Price_Onetime', models.IntegerField()),
                ('package_duration', models.DateField()),
                ('package_Cancelation', models.BooleanField()),
                ('package_Booking', models.BooleanField()),
                ('package_Access_Rules', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_Name', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('date_Birth', models.DateField()),
                ('Company', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('tax_Exempt', models.BooleanField()),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('zip_Code', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('billing_Opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Billing_opt')),
                ('package_Opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Package_opt')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Training')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_Hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Opening_hours'),
        ),
        migrations.AddField(
            model_name='facility',
            name='package_Opt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Package_opt'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='training',
            field=models.ManyToManyField(to='quickstart.Training'),
        ),
        migrations.AddField(
            model_name='booking_schedule',
            name='booking_Equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Equipment'),
        ),
        migrations.AddField(
            model_name='booking_schedule',
            name='booking_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.User_account'),
        ),
        migrations.AddField(
            model_name='activity_log',
            name='log_Equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Equipment'),
        ),
        migrations.AddField(
            model_name='activity_log',
            name='log_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.User_account'),
        ),
    ]
