# Generated by Django 2.0.13 on 2019-04-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='log_Equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Equipment'),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='log_User',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.User_account'),
        ),
        migrations.AlterField(
            model_name='booking_schedule',
            name='booking_Equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Equipment'),
        ),
        migrations.AlterField(
            model_name='booking_schedule',
            name='booking_User',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.User_account'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_Bridge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Bridge'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='billing_Opt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Billing_opt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='booking_Opt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Booking_opt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='opening_Hours',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Opening_hours'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='package_Opt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Package_opt'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='billing_Opt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Billing_opt'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='package_Opt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Package_opt'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='training',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.Training'),
        ),
    ]
