# Generated by Django 2.0.13 on 2019-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190410_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_Tag', models.CharField(max_length=20)),
                ('auth', models.BooleanField()),
            ],
        ),
    ]
